### ISSUE TITLE
Loads of corrections

### ISSUE THREAD

**Issue by nordlow** [ontologyportal/sumo#199] opened 2019-12-16 10:45 UTC
Here's my load of additions/corrections my own SUO-KIF-analyzer detected:

https://github.com/nordlow/sumo/commit/a196094f31c9cd17c19234f63733d7028b622ea8

I've not completed the corrections in `mondial.kif` since it seems to be very unmaintained containing lots of undefined predicates.

I've commented out the `format` and `termFomat` definitions of undefined (or commented out) predicates and functions. For instance `AbstractionFn` is commented out in `Merge.kif`.

Note that my analyzer requires all predicates/functions to be defined using the statements

```
(instance somePredicate ${ARITY}Predicate)
(instance SomeFunctionFn ${ARITY}Function)
```

alongside their other definitions such as `subrelation`. I believe this is a good idea for clarity. It also enables more memory-efficient direct (static array) storage of domain-arrays inside predicates and functions in languages supporting static array storage. Alternative I could extend representations in the parser to lookup arity via `subrelation` links if you think this is an unneccessary requirement.

Do you want this split up in any way? One PR per file?

**Comment by nordlow** [comment] 2019-12-17 15:43
Ping

**Comment by apease** [comment] 2019-12-17 15:44
sorry I couldn't reply yesterday, will look at this today

**Comment by apease** [comment] 2019-12-17 16:10
I think I may have to look at these individually and correct them, rather than doing it by PR.  For example, you've found that properPartType is missing its domain statements, but it's actually missing all its definition, since it's just a typo and partType was the correct relation to use.  So, we have to find the root cause of each error

**Comment by apease** [comment] 2019-12-17 16:11
partTypes I mean

**Comment by nordlow** [comment] 2019-12-17 18:59
You are more than welcome to do all these corrections yourself, @apease :)

Tell me if you need any help.

**Comment by apease** [comment] 2019-12-18 19:45
I've incorporate these and pushed and merged.  I recommend doing a pull to stay in sync.  Many thanks for all this!

**Closed** 2019-12-18 21:01 UTC
